# Azure Pipeline settings
# Ref: https://docs.microsoft.com/en-us/azure/devops/pipelines

jobs:
  - job: linux
    pool: { vmImage: "Ubuntu-16.04" }
    steps:
      - task: UsePythonVersion@0
      - bash: |
          cd ci/manylinux
          ./build_wheels.sh
      - task: PublishBuildArtifacts@1
        inputs: { pathtoPublish: "wheelhouse" }

  - job: macos
    pool: { vmImage: "macOS-10.15" }
    steps:
      - task: UsePythonVersion@0
      - bash: |
          cd ci/mac
          ./mac.sh
          ./build_wheels.sh
      - task: PublishBuildArtifacts@1
        inputs: { pathtoPublish: "wheelhouse" }
