# Azure Pipeline settings
# Ref: https://docs.microsoft.com/en-us/azure/devops/pipelines

jobs:
- job: xenial_gcc_debug
  timeoutInMinutes: 120
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    COMPILER: gcc
    BUILD_TYPE: Debug
    BUILD_DIR: $(Build.SourcesDirectory)
    DOCKERFILE: Dockerfile.ubuntu-xenial
  steps:
  - template: .ci/azure-pipelines/docker.yml

- job: bionic_gcc_debug
  timeoutInMinutes: 120
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    COMPILER: gcc
    BUILD_TYPE: Debug
    BUILD_DIR: $(Build.SourcesDirectory)
    DOCKERFILE: Dockerfile.ubuntu-bionic
  steps:
  - template: .ci/azure-pipelines/docker.yml

- job: eoan_gcc_debug
  timeoutInMinutes: 120
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    COMPILER: gcc
    BUILD_TYPE: Debug
    BUILD_DIR: $(Build.SourcesDirectory)
    DOCKERFILE: Dockerfile.ubuntu-eoan
  steps:
  - template: .ci/azure-pipelines/docker.yml

- job: focal_gcc_debug
  timeoutInMinutes: 120
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    COMPILER: gcc
    BUILD_TYPE: Debug
    BUILD_DIR: $(Build.SourcesDirectory)
    DOCKERFILE: Dockerfile.ubuntu-focal
  steps:
  - template: .ci/azure-pipelines/docker.yml

- job: mojav_clang_debug
  timeoutInMinutes: 120
  pool:
    vmImage: 'macOS-10.15'
  variables:
    BUILD_TYPE: Debug
    BUILD_DIR: $(Build.SourcesDirectory)
  steps:
  - script: |
      '.ci/install.sh'
    displayName: 'Install'
  - script: |
      '.ci/script.sh'
    displayName: 'Script'

- job: windows_vs2019_x64
  timeoutInMinutes: 120
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      Debug64:
        CONFIGURATION: 'Debug'
      # Release64:
      #   CONFIGURATION: 'Release'
  variables:
    VCPKG_INSTALL_ROOT: $(Build.SourcesDirectory)\dartsim\vcpkg
    VCPKG_BUILD_TAG: v0.1.0
    BUILD_TOOLSET_VERSION: '142'
    CMAKE_GENERATOR: 'Visual Studio 16 2019'
  steps:
  - script: |
      mkdir -p $(Build.SourcesDirectory)\dartsim
      choco install -y wget
      wget https://github.com/jslee02/vcpkg-build/releases/download/%VCPKG_BUILD_TAG%/vcpkg-dartsim-dependencies.zip
      unzip vcpkg-dartsim-dependencies.zip -d $(Build.SourcesDirectory)\dartsim
    displayName: 'Install dependencies'
  - script: |
      cmake --version
      mkdir build
      cd build
      cmake .. -G "$(CMAKE_GENERATOR)" -A x64 -DCMAKE_BUILD_TYPE=$(CONFIGURATION) -Wno-dev -T "v$(BUILD_TOOLSET_VERSION),host=x64" -DVCPKG_TARGET_TRIPLET=$(VCPKG_ARCH) -DCMAKE_TOOLCHAIN_FILE="$(VCPKG_INSTALL_ROOT)/scripts/buildsystems/vcpkg.cmake" -DCMAKE_INSTALL_PREFIX="$(Build.BinariesDirectory)/$(REPO_NAME)" -DDART_MSVC_DEFAULT_OPTIONS=ON -DDART_VERBOSE=ON
      cmake --build . --target ALL_BUILD --config $(CONFIGURATION) -- /maxcpucount:4
    displayName: 'Build'
    workingDirectory: '$(Build.SourcesDirectory)'
